---

# Requirements
- name: requirements
  assert:
    that:
      - manala_deploy_dir
      - manala_deploy_checkout == 'git' and manala_deploy_checkout_git_repository
    msg: |
      You must set "manala_deploy_dir"
      You must set "manala_deploy_checkout_git_repository" if "manala_deploy_checkout" is "git"
  always_run: true
  tags:
    - manala_deploy

# Structure
- include: structure.yml
  when: "{{ manala_deploy['structure']|default(true) }}"
  tags:
    - manala_deploy
    - manala_deploy.structure

# Checkout
- include: "checkout/{{ manala_deploy_checkout }}.yml"
  when: "{{ manala_deploy['checkout']|default(true) }}"
  tags:
    - manala_deploy
    - manala_deploy.checkout

# Tasks
- block:
    - include: tasks/{{ item.task }}.yml
      with_manala_deploy_tasks: "{{ manala_deploy_tasks }}"
      when: "{{ item.when }}"
  when: "{{ manala_deploy['tasks']|default(true) }}"
  tags:
    - manala_deploy
    - manala_deploy.tasks

# Release
- include: release.yml
  when: "{{ manala_deploy['release']|default(true) }}"
  tags:
    - manala_deploy
    - manala_deploy.release

# Post tasks
- block:
    - include: tasks/{{ item.task }}.yml
      with_manala_deploy_tasks: "{{ manala_deploy_post_tasks }}"
      when: "{{ item.when }}"
  when: "{{ manala_deploy['post_tasks']|default(true) }}"
  tags:
    - manala_deploy
    - manala_deploy.post_tasks
