---

- name: strategy/git > Update repository
  git:
    repo:           "{{ manala_deploy_strategy_git_repo }}"
    dest:           "{{ manala_deploy_dir ~ '/repo' }}"
    version:        "{{ manala_deploy_strategy_git_version }}"
    accept_hostkey: true
    update:         true
    force:          true

- name: strategy/git > Create release folder
  file:
    state: directory
    path: "{{ deploy_helper.new_release_path }}"

- name: strategy/git > Export repository
  shell: git archive --format=tar {{ manala_deploy_strategy_git_version }} | tar -x -f - -C "{{ deploy_helper.new_release_path }}"
  args:
    chdir: "{{ manala_deploy_dir ~ '/repo' }}"
