---

- name: tasks/symfony_assets_version_file > Generate assets_version.yml
  copy:
    dest: "{{ item.dir }}/app/config/assets_version.yml"
    force: yes
    content: |
      parameters:
        assets_version: {{ manala_deploy_strategy_git_head }}
    when: "{{ manala_deploy_strategy_git_head }}"
